libmysqlclient.so.18: cannot open shared object file: No such file or directory
No module named PyQt4.QtGui
Leave-one-out test found 596 suspicious sequences; running final two to check them...

Processed 11939 sequences in 45128 seconds.

