libmysqlclient.so.18: cannot open shared object file: No such file or directory
No module named PyQt4.QtGui
Leave-one-out test found 609 suspicious sequences; running final test to check them...

Processed 11939 sequences in 6 seconds.

